### ISSUE TITLE
How to train?

### ISSUE THREAD

**Issue by tuberboy** [siyuanseever/llama2Rnn.c#1]
I want to learn how to train model, like you did: toy and little. Suggest me videos or tech me. Also add train, tokenizer, transformer etc C files on your repo. Thanks in advance

**Comment by siyuanseever** [comment]
I will release the traning code next week.

**Comment by tuberboy** [comment]
> I will release the traning code next week.

ok, waiting
I want to train my own dataset. Hope so your train code will allow me to do that, thanks

**Comment by emma-eva** [comment]
can you share with me recent train code? which you used for toy and little model?

**Comment by emma-eva** [comment]
What's you updated? where is old files? I don't understand which codes you used to train little and toy model

**Comment by siyuanseever** [comment]
Since the repo was forked from llama2.c, you can now see many historical commits; the inference code and usage steps should be consistent with the original; [here](https://github.com/siyuanseever/llama2Rnn.c/blob/main/README.en.md#how-to-train) is a simple training guide.

**Comment by siyuanseever** [comment]
> What's you updated? where is old files? I don't understand which codes you used to train little and toy model

Since the repo was forked from llama2.c, you can now see many historical commits; the inference code and usage steps should be consistent with the original; [here](https://github.com/siyuanseever/llama2Rnn.c/blob/main/README.en.md#how-to-train) is a simple training guide.
