### ISSUE TITLE
項目訓練中的上下文該如何調整呢?

### ISSUE THREAD

**Issue by win10ogod** [siyuanseever/llama2Rnn.c#4]
項目訓練中的上下文該如何調整呢?
Traceback (most recent call last):
  File "/llama2Rnn/train.py", line 147, in <module>
    assert gradient_accumulation_steps % ddp_world_size == 0

**Comment by win10ogod** [comment]
@siyuanseever 
這是我的設置但出現報錯
```
max_seq_len = 4096
init_from = "scratch"

# memory
# attention_type = "attention"
attention_type = "memory_attention"
extend_method = "logn_train"
key_norm = True

memseqlen = 64 // 2
```

**Comment by siyuanseever** [comment]
> 項目訓練中的上下文該如何調整呢? Traceback (most recent call last): File "/llama2Rnn/train.py", line 147, in assert gradient_accumulation_steps % ddp_world_size == 0

这里似乎是说你的GPU数量并不能被gradient_accumulation_steps整除，你可以看下你使用的DDP时的world_size，或者调整下gradient_accumulation_steps的数值。

另外这个repo只是个实验性质的，工程稳定性可能写的不会太好。

**Comment by win10ogod** [comment]
> > 項目訓練中的上下文該如何調整呢? Traceback (most recent call last): File "/llama2Rnn/train.py", line 147, in assert gradient_accumulation_steps % ddp_world_size == 0
> 
> 这里似乎是说你的GPU数量并不能被gradient_accumulation_steps整除，你可以看下你使用的DDP时的world_size，或者调整下gradient_accumulation_steps的数值。
> 
> 另外这个repo只是个实验性质的，工程稳定性可能写的不会太好。

能向你請教一下,如果修改過建模 ,runqm.c等文件是需要修改的嗎?

**Comment by win10ogod** [comment]
還有你有近一步完善項目的計畫嗎?
真的很期待
